apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
  namespace: cert-manager
spec:
  acme:
    # Let's Encrypt will use this email to contact you about expiring
    # certificates, and issues related to your account.
    email: crownlabs2020@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource used to store the account's private key.
      name: letsencrypt-production-private-key
    solvers:
    - http01:
        ingress:
          class: nginx-external
    - dns01:
        rfc2136:
          nameserver: 130.192.225.79
          tsigKeyName: crownlabs-certmanager
          tsigAlgorithm: HMACSHA512
          tsigSecretSecretRef:
            name: crownlabs-certmanager-tsig
            key: crownlabs-certmanager-tsig-key
      selector:
        dnsZones:
        - crownlabs.polito.it
        matchLabels:
          use-dns01-solver: "true"
    - dns01:
        rfc2136:
          nameserver: 130.192.225.79
          tsigKeyName: crownlabs-internal-certmanager
          tsigAlgorithm: HMACSHA512
          tsigSecretSecretRef:
            name: crownlabs-internal-certmanager-tsig
            key: crownlabs-internal-certmanager-tsig-key
      selector:
        dnsZones:
          - internal.crownlabs.polito.it
        matchLabels:
          use-dns01-solver: "true"
