run:
  skip-files:
    - "zz_generated.*.go"

linters-settings:
  exhaustive:
    check-generated: false
    default-signifies-exhaustive: true
  gci:
    local-prefixes: github.com/netgroup-polito/CrownLabs
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      # Conflicts with govet check-shadowing
      - sloppyReassign
  goimports:
    local-prefixes: github.com/netgroup-polito/CrownLabs
  govet:
    check-shadowing: true
  misspell:
    locale: US
  nolintlint:
    allow-leading-space: true # don't require machine-readable nolint directives (i.e. with no leading space)
    allow-unused: false # report any unused nolint directives
    require-explanation: true # require an explanation for nolint directives
    require-specific: true # require nolint directives to be specific about which linter is being skipped

linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - errorlint
    - exhaustive
    - exportloopref
  # - funlen
  # - gochecknoglobals
  # - gochecknoinits
    - gci
  # - gocognit
  # - goconst
    - gocritic
    - gocyclo
    - godot
  # - godox
  # - goerr113
    - gofmt
    - goimports
    - gomodguard
  # - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
  # - lll
  # - maligned
    - misspell
    - nakedret
  # - nestif
    - noctx
    - nolintlint
  # - prealloc
    - revive
    - rowserrcheck
    - staticcheck
    - structcheck
    - stylecheck
  # - testpackage
    - typecheck
    - unconvert
  # - unparam
    - unused
    - varcheck
    - whitespace
  # - wsl

issues:
  # Disable the default exclude patterns (as they disable the mandatory comments)
  exclude-use-default: false
  exclude:
    # errcheck: Almost all programs ignore errors on these functions and in most cases it's ok
    - Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv). is not checked

  exclude-rules:
    - linters:
        - govet
      text: 'declaration of "(err|ctx)" shadows declaration at'

    - linters:
        - revive
      # Excluding, as many packages are currently affected by this
      text: "don't use an underscore in package name"

    - linters:
        - stylecheck
      # Excluding, as many packages are currently affected by this
      text: "ST1003: should not use underscores in package names"
